// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Report struct {
	ID string `json:"id"`
}

type Service struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Schema  string `json:"schema"`
}

type User struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Reports []*Report `json:"reports"`
}
