// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Report struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

type Service struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Schema  string `json:"schema"`
}
